# Generated by Django 3.2.16 on 2023-01-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2022-05-12'),
            preserve_default=False,
        ),
    ]
